### ISSUE TITLE
[Compatibility] Not hiding GM fomulas when using "Hide GM Rolls" module

### ISSUE THREAD

**Issue by joshua-igor** [jessev14/better-dice-tooltips#1]
The module Hide GM Rolls has an option to hide the formula of a GM roll so the players won't know how much bonus the enemy has. The player should only see the total result of the roll when using this mod.
Unfortunately, when you activate Better Dice Formulas it overwrites this functionality, showing the players the formulas for the GM roll.

**Comment by jessev14** [comment]
Addressed in v1.1.0.
